version: '3.8'

services:
  calculator:
    build: .
    ports:
      - "8081:3000"  # Map local port 8080 to container port 3000
    container_name: calculator-container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]  # Use 8080 for healthcheck
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always
